version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto8
  build:
    commands:
    - echo Running tests 
    - mvn clean test
    - mvn clean package
reports:
  StateMachineReports:
    files:
      - "**/*"
    base-directory: "reports"
