version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto8
  build:
    commands:
    - echo Running tests 
    - mvn test
    - mvn clean package
    
reports:
  php-reports:
    files:
      - "src/test/java/com/mt/sample/test/HelloWorldTest.java"
    file-format: "JUNITXML"
