version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto8
  build:
    commands:
    - echo Running JUNIT tests 
    - mvn clean test 
       
reports:
  arn:aws:codebuild:ap-south-1:091416694046:report-group/shatestgroup:
    files:
      - "**/*"
    discard-paths: yes
    
